# Generated by Django 4.1.4 on 2022-12-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('surname', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(blank=True, default='', null=True)),
                ('subject', models.CharField(choices=[('games', 'Games'), ('consulting', 'Consulting'), ('marketing', 'Marketing of games'), ('licence and deploying', 'Licence and Deploying'), ('other question', 'Other question')], max_length=40)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
