# Generated by Django 4.1.4 on 2022-12-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
