# Generated by Django 4.1.4 on 2022-12-24 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_feedback_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[\\+]\\d{5,15}$')]),
        ),
    ]
